### PR TITLE
Grid column

### PR DESCRIPTION
**Pull request by swinde**
### summernote-grid

A Summernote plugin that adds a button to the toolbar allowing the user to create custom grid columns.
https://github.com/perevoshchikov/summernote-grid

### CODE REVIEW

**Comment by Sieg** [comment]
Hey @swinde, thanks for the Pull request!

I havent checked how it works yet, but i see you have removed quite a lot of buttons from the panel, thats not good.

**Comment by swinde** [comment]
Hey @Sieg, thanks for looking!
The pull request should actually only add the plugin! I only removed the button for the test! I just don't know how to remove it!
Unfortunately, when testing the PR, I noticed that the editor no longer works in various shops! Please don't merge the PR first! 
PS: Could we also write in German? That would make it easier!

**Comment by Sieg** [comment]
Hey @swinde, sorry, i dont know German good enough ;) Regarding the PR, for sure it will not be merged till its fully tested and finalized, no worries!

**Comment by Sieg** [comment]
Origin of the plugin: https://github.com/perevoshchikov/summernote-grid

**Comment by Sieg** [comment]
Hey @swinde, I have tried this up. Looks not very stable, and doesnt work very well:
* Editing those columns is real pain, if you remove the default text, it breaks.
* If you try to put this grid after some text it breaks
* After saving the CMS content with the grid, it doesnt show it nice anymore

So, looks like, this plugin requires much more configuration, or maybe even some finalizing, for making it possible to use in our environment.

Thanks for your try, but we cannot take it at this state. Feel free to reopen the pull request if improvements will be done.

In case you will improve/reconfigure it, please add original license text to the start of plugin file, as its required by plugin creator.

Feel free to use pr16 branch from the module repository, it have some small fixes for your changes from my side.

Have a nice day.

**Pull request closed without merging**
